version: '3.8'
services:
  bot:
    build: .
    container_name: aiogram-bot
    env_file:
      - .env
    volumes:
      - .:/app
    command: python main.py
    # ports: ["8000:8000"]  # если нужен внешний порт
    restart: unless-stopped
    # depends_on:
    #   - db
  # db:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: botdb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
#volumes:
#  pgdata:
